// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: birds.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createBird = `-- name: CreateBird :one
INSERT INTO birds  (id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls)
VALUES ( 
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) ON CONFLICT (common_name) DO UPDATE SET updated_at = NOW(), status = $5, image_urls = $6
RETURNING id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls
`

type CreateBirdParams struct {
	CommonName     sql.NullString
	ScientificName sql.NullString
	Family         sql.NullString
	Order          sql.NullString
	Status         sql.NullString
	ImageUrls      []string
}

func (q *Queries) CreateBird(ctx context.Context, arg CreateBirdParams) (Bird, error) {
	row := q.db.QueryRowContext(ctx, createBird,
		arg.CommonName,
		arg.ScientificName,
		arg.Family,
		arg.Order,
		arg.Status,
		pq.Array(arg.ImageUrls),
	)
	var i Bird
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommonName,
		&i.ScientificName,
		&i.Family,
		&i.Order,
		&i.Status,
		pq.Array(&i.ImageUrls),
	)
	return i, err
}

const getAllBirds = `-- name: GetAllBirds :many
SELECT id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls from birds
`

func (q *Queries) GetAllBirds(ctx context.Context) ([]Bird, error) {
	rows, err := q.db.QueryContext(ctx, getAllBirds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bird
	for rows.Next() {
		var i Bird
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommonName,
			&i.ScientificName,
			&i.Family,
			&i.Order,
			&i.Status,
			pq.Array(&i.ImageUrls),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImageUrls = `-- name: GetAllImageUrls :many
SELECT image_urls from birds WHERE image_urls IS NOT NULL
`

func (q *Queries) GetAllImageUrls(ctx context.Context) ([][]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllImageUrls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]string
	for rows.Next() {
		var image_urls []string
		if err := rows.Scan(pq.Array(&image_urls)); err != nil {
			return nil, err
		}
		items = append(items, image_urls)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBirdByID = `-- name: GetBirdByID :one
SELECT id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls from birds
WHERE id = $1
`

func (q *Queries) GetBirdByID(ctx context.Context, id uuid.UUID) (Bird, error) {
	row := q.db.QueryRowContext(ctx, getBirdByID, id)
	var i Bird
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommonName,
		&i.ScientificName,
		&i.Family,
		&i.Order,
		&i.Status,
		pq.Array(&i.ImageUrls),
	)
	return i, err
}

const getBirdsForCaching = `-- name: GetBirdsForCaching :many
SELECT id, image_urls FROM birds WHERE image_urls IS NOT NULL
`

type GetBirdsForCachingRow struct {
	ID        uuid.UUID
	ImageUrls []string
}

func (q *Queries) GetBirdsForCaching(ctx context.Context) ([]GetBirdsForCachingRow, error) {
	rows, err := q.db.QueryContext(ctx, getBirdsForCaching)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBirdsForCachingRow
	for rows.Next() {
		var i GetBirdsForCachingRow
		if err := rows.Scan(&i.ID, pq.Array(&i.ImageUrls)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomBird = `-- name: GetRandomBird :many
SELECT id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls from birds
ORDER by RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomBird(ctx context.Context, limit int32) ([]Bird, error) {
	rows, err := q.db.QueryContext(ctx, getRandomBird, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bird
	for rows.Next() {
		var i Bird
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommonName,
			&i.ScientificName,
			&i.Family,
			&i.Order,
			&i.Status,
			pq.Array(&i.ImageUrls),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomBirdWithImage = `-- name: GetRandomBirdWithImage :many
SELECT id, created_at, updated_at, common_name, scientific_name, family, "order", status, image_urls from birds
WHERE image_urls is NOT NULL
ORDER by RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomBirdWithImage(ctx context.Context, limit int32) ([]Bird, error) {
	rows, err := q.db.QueryContext(ctx, getRandomBirdWithImage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bird
	for rows.Next() {
		var i Bird
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommonName,
			&i.ScientificName,
			&i.Family,
			&i.Order,
			&i.Status,
			pq.Array(&i.ImageUrls),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalBirdCount = `-- name: GetTotalBirdCount :one
SELECT count(*) from birds
`

func (q *Queries) GetTotalBirdCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalBirdCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateBirdImageUrls = `-- name: UpdateBirdImageUrls :exec
UPDATE birds SET image_urls = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBirdImageUrlsParams struct {
	ID        uuid.UUID
	ImageUrls []string
}

func (q *Queries) UpdateBirdImageUrls(ctx context.Context, arg UpdateBirdImageUrlsParams) error {
	_, err := q.db.ExecContext(ctx, updateBirdImageUrls, arg.ID, pq.Array(arg.ImageUrls))
	return err
}
