// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cleanUpSessions = `-- name: CleanUpSessions :exec
DELETE FROM match_sessions
WHERE expires_at < NOW() - INTERVAL '1 day'
`

func (q *Queries) CleanUpSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanUpSessions)
	return err
}

const createMatchSession = `-- name: CreateMatchSession :one
INSERT INTO match_sessions(
    id, 
    created_at, 
    leftbird_id, 
    rightbird_id, 
    session_token, 
    expires_at, 
    user_ip, 
    user_agent
)
VALUES ( 
    gen_random_uuid(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, created_at, leftbird_id, rightbird_id, session_token, expires_at, voted, voted_at, winnerbird_id, user_ip, user_agent
`

type CreateMatchSessionParams struct {
	LeftbirdID   uuid.UUID
	RightbirdID  uuid.UUID
	SessionToken string
	ExpiresAt    time.Time
	UserIp       sql.NullString
	UserAgent    sql.NullString
}

func (q *Queries) CreateMatchSession(ctx context.Context, arg CreateMatchSessionParams) (MatchSession, error) {
	row := q.db.QueryRowContext(ctx, createMatchSession,
		arg.LeftbirdID,
		arg.RightbirdID,
		arg.SessionToken,
		arg.ExpiresAt,
		arg.UserIp,
		arg.UserAgent,
	)
	var i MatchSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LeftbirdID,
		&i.RightbirdID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.Voted,
		&i.VotedAt,
		&i.WinnerbirdID,
		&i.UserIp,
		&i.UserAgent,
	)
	return i, err
}

const getMatchSessionById = `-- name: GetMatchSessionById :one
SELECT id, created_at, leftbird_id, rightbird_id, session_token, expires_at, voted, voted_at, winnerbird_id, user_ip, user_agent FROM match_sessions
WHERE id = $1
`

func (q *Queries) GetMatchSessionById(ctx context.Context, id uuid.UUID) (MatchSession, error) {
	row := q.db.QueryRowContext(ctx, getMatchSessionById, id)
	var i MatchSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LeftbirdID,
		&i.RightbirdID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.Voted,
		&i.VotedAt,
		&i.WinnerbirdID,
		&i.UserIp,
		&i.UserAgent,
	)
	return i, err
}

const getMatchSessionByToken = `-- name: GetMatchSessionByToken :one
SELECT id, created_at, leftbird_id, rightbird_id, session_token, expires_at, voted, voted_at, winnerbird_id, user_ip, user_agent FROM match_sessions
WHERE session_token = $1
`

func (q *Queries) GetMatchSessionByToken(ctx context.Context, sessionToken string) (MatchSession, error) {
	row := q.db.QueryRowContext(ctx, getMatchSessionByToken, sessionToken)
	var i MatchSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LeftbirdID,
		&i.RightbirdID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.Voted,
		&i.VotedAt,
		&i.WinnerbirdID,
		&i.UserIp,
		&i.UserAgent,
	)
	return i, err
}

const voteMatch = `-- name: VoteMatch :one
UPDATE match_sessions
SET voted = TRUE,
    voted_at = NOW(),
    winnerbird_id = $2
WHERE id = $1
RETURNING id, created_at, leftbird_id, rightbird_id, session_token, expires_at, voted, voted_at, winnerbird_id, user_ip, user_agent
`

type VoteMatchParams struct {
	ID           uuid.UUID
	WinnerbirdID uuid.NullUUID
}

func (q *Queries) VoteMatch(ctx context.Context, arg VoteMatchParams) (MatchSession, error) {
	row := q.db.QueryRowContext(ctx, voteMatch, arg.ID, arg.WinnerbirdID)
	var i MatchSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LeftbirdID,
		&i.RightbirdID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.Voted,
		&i.VotedAt,
		&i.WinnerbirdID,
		&i.UserIp,
		&i.UserAgent,
	)
	return i, err
}
