// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllMatches = `-- name: GetAllMatches :many
SELECT id, created_at, updated_at, winnerbird_id, loserbird_id from matches
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetAllMatches(ctx context.Context, limit int32) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getAllMatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WinnerbirdID,
			&i.LoserbirdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, created_at, updated_at, winnerbird_id, loserbird_id from matches
WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WinnerbirdID,
		&i.LoserbirdID,
	)
	return i, err
}

const getMatchByParticipants = `-- name: GetMatchByParticipants :many
SELECT id, created_at, updated_at, winnerbird_id, loserbird_id from matches
WHERE (winnerbird_id = $1 OR loserbird_id = $1)
`

func (q *Queries) GetMatchByParticipants(ctx context.Context, winnerbirdID uuid.UUID) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getMatchByParticipants, winnerbirdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WinnerbirdID,
			&i.LoserbirdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMatch = `-- name: RecordMatch :one
INSERT INTO matches (id, created_at, updated_at, winnerbird_id, loserbird_id)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
) RETURNING id, created_at, updated_at, winnerbird_id, loserbird_id
`

type RecordMatchParams struct {
	WinnerbirdID uuid.UUID
	LoserbirdID  uuid.UUID
}

func (q *Queries) RecordMatch(ctx context.Context, arg RecordMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, recordMatch, arg.WinnerbirdID, arg.LoserbirdID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WinnerbirdID,
		&i.LoserbirdID,
	)
	return i, err
}
