// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bird struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CommonName     sql.NullString
	ScientificName sql.NullString
	Family         sql.NullString
	Order          sql.NullString
	Status         sql.NullString
	ImageUrls      []string
}

type Match struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	WinnerbirdID uuid.UUID
	LoserbirdID  uuid.UUID
}

type MatchSession struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	LeftbirdID   uuid.UUID
	RightbirdID  uuid.UUID
	SessionToken string
	ExpiresAt    time.Time
	Voted        sql.NullBool
	VotedAt      sql.NullTime
	WinnerbirdID uuid.NullUUID
	UserIp       sql.NullString
	UserAgent    sql.NullString
}

type Rating struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Matches    sql.NullInt32
	Rating     sql.NullInt32
	BirdID     uuid.UUID
	CommonName sql.NullString
}
