name: Deploy to GCP

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    environment: GCP

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: '${{ secrets.PROJECT_ID }}'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/go-app:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Setup Cloud SQL Proxy'
        run: |-
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.21.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy ${{ secrets.PROJECT_ID }}:${{ secrets.REGION }}:${{ secrets.DB_INSTANCE }}=tcp:5432 &
          sleep 5  

      - name: 'Run database migrations'
        run: |-
          go install github.com/pressly/goose/v3/cmd/goose@latest
          goose -dir ./sql/schema postgres "${{ secrets.DB_URL }}" up

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ secrets.SERVICE }}'
          region: '${{ secrets.REGION }}'
          image: '${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/go-app:${{ github.sha }}'
          env_vars: |-
            DB_URL=${{ secrets.DB_URL }}
            NUTHATCH_KEY=${{ secrets.NUTHATCH_KEY }}

      - name: 'Show output'
        run: echo "${ steps.deploy.outputs.url }"